version: 2.1
jobs:
  build:
    working_directory: ~/bcp
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run tests
          command: npm run test
      # - run: cat ./coverage/coverage.json
      - store_artifacts:
          path: ~/bcp/artifacts
